<script>
  import { ModalContent, Layout, notifications, Body } from "@budibase/bbui"
  import { datasources } from "stores/backend"
  import ICONS from "components/backend/DatasourceNavigator/icons"
  import { IntegrationNames } from "constants"
  import { onMount } from "svelte"
  import rowListScreen from "builderStore/store/screenTemplates/rowListScreen"
  import DatasourceTemplateRow from "./DatasourceTemplateRow.svelte"

  export let onCancel
  export let onConfirm
  export let initialScreens = []

  let selectedScreens = [...initialScreens]

  $: filteredSources = $datasources.list?.filter(datasource => {
    return datasource.source !== IntegrationNames.REST && datasource["entities"]
  })

  const toggleSelection = datasource => {
    const { resourceId } = datasource
    if (selectedScreens.find(s => s.resourceId === resourceId)) {
      selectedScreens = selectedScreens.filter(
        screen => screen.resourceId !== resourceId
      )
    } else {
      selectedScreens = [...selectedScreens, rowListScreen([datasource])[0]]
    }
  }

  const confirmDatasourceSelection = async () => {
    await onConfirm({
      templates: selectedScreens,
    })
  }

  onMount(async () => {
    try {
      await datasources.fetch()
    } catch (error) {
      notifications.error("Error fetching datasources")
    }
  })
</script>

<span>
  <ModalContent
    title="Autogenerated screens"
    confirmText="Confirm"
    cancelText="Back"
    onConfirm={confirmDatasourceSelection}
    {onCancel}
    disabled={!selectedScreens.length}
    size="L"
  >
    <Body size="S">
      Select which datasources you would like to use to create your screens
    </Body>
    <Layout noPadding gap="S">
      {#each filteredSources as datasource}
        {@const entities = Array.isArray(datasource.entities)
          ? datasource.entities
          : Object.values(datasource.entities || {})}
        <div class="data-source-wrap">
          <div class="data-source-header">
            <svelte:component
              this={ICONS[datasource.source]}
              height="24"
              width="24"
            />
            <div class="data-source-name">{datasource.name}</div>
          </div>
          <!-- List all tables -->
          {#each entities.filter(table => table._id !== "ta_users") as table}
            {@const views = Object.values(table.views || {}).filter(
              view => view.version === 2
            )}
            {@const tableDS = {
              tableId: table._id,
              label: table.name,
              resourceId: table._id,
              type: "table",
            }}
            {@const selected = selectedScreens.find(
              screen => screen.resourceId === tableDS.resourceId
            )}
            <DatasourceTemplateRow
              on:click={() => toggleSelection(tableDS)}
              {selected}
              datasource={tableDS}
            />

            <!-- List all views inside this table -->
            {#each views as view}
              {@const viewDS = {
                label: view.name,
                id: view.id,
                resourceId: view.id,
                tableId: view.tableId,
                type: "viewV2",
              }}
              {@const selected = selectedScreens.find(
                x => x.resourceId === viewDS.resourceId
              )}
              <DatasourceTemplateRow
                on:click={() => toggleSelection(viewDS)}
                {selected}
                datasource={viewDS}
              />
            {/each}
          {/each}
        </div>
      {/each}
    </Layout>
  </ModalContent>
</span>

<style>
  .data-source-wrap {
    padding-bottom: var(--spectrum-alias-item-padding-s);
    display: grid;
    grid-gap: var(--spacing-s);
  }
  .data-source-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-m);
    padding-bottom: var(--spacing-xs);
  }
</style>
