version: "3.8"
services:
  # password: Passw0rd
  # user: sa
  # database: master
  mssql:
    # platform: linux/amd64
    image: bb/mssql
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - "1433:1433"

  admin-ui:
    image: dbgate/dbgate
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      CONNECTIONS: mssql
      LABEL_mssql: MSSQL
      SERVER_mssql: mssql
      PORT_mssql: 1433
      USER_mssql: sa
      PASSWORD_mssql: Passw0rd
      ENGINE_mssql: mssql@dbgate-plugin-mssql
