{{- if .Values.services.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-data
  name: redis-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.redis.storage }}
  {{ if .Values.services.redis.storageClass }}
  storageClassName: {{ .Values.services.redis.storageClass }}
  {{ end }}
status: {}
{{- end }}
