const componentLoaders = {
  placeholder: () => import("./Placeholder.svelte"),
  container: () => import("./container/Container.svelte"),
  dataprovider: () => import("./DataProvider.svelte"),
  divider: () => import("./Divider.svelte"),
  screenslot: () => import("./ScreenSlot.svelte"),
  button: () => import("./Button.svelte"),
  buttongroup: () => import("./ButtonGroup.svelte"),
  repeater: () => import("./Repeater.svelte"),
  layout: () => import("./Layout.svelte"),
  link: () => import("./Link.svelte"),
  image: () => import("./Image.svelte"),
  embed: () => import("./Embed.svelte"),
  icon: () => import("./Icon.svelte"),
  iconphosphor: () => import("./IconV2.svelte"),
  backgroundimage: () => import("./BackgroundImage.svelte"),
  daterangepicker: () => import("./DateRangePicker.svelte"),
  cardstat: () => import("./CardStat.svelte"),
  spectrumcard: () => import("./SpectrumCard.svelte"),
  tag: () => import("./Tag.svelte"),
  embeddedmap: () => import("./embedded-map/EmbeddedMap.svelte"),
  sidepanel: () => import("./SidePanel.svelte"),
  modal: () => import("./Modal.svelte"),
  gridblock: () => import("./GridBlock.svelte"),
  textv2: () => import("./Text.svelte"),
  filter: () => import("./filter/Filter.svelte"),
  accordion: () => import("./Accordion.svelte"),
  singlerowprovider: () => import("./SingleRowProvider.svelte"),
  codegenerator: () => import("./CodeGenerator.svelte"),
  // Charts
  bar: () => import("./charts/BarChart.svelte"),
  line: () => import("./charts/LineChart.svelte"),
  pie: () => import("./charts/PieChart.svelte"),
  donut: () => import("./charts/DonutChart.svelte"),
  area: () => import("./charts/AreaChart.svelte"),
  candlestick: () => import("./charts/CandleStickChart.svelte"),
  histogram: () => import("./charts/HistogramChart.svelte"),
  // Forms
  form: () => import("./forms/Form.svelte"),
  fieldgroup: () => import("./forms/FieldGroup.svelte"),
  stringfield: () => import("./forms/StringField.svelte"),
  numberfield: () => import("./forms/NumberField.svelte"),
  bigintfield: () => import("./forms/BigIntField.svelte"),
  optionsfield: () => import("./forms/OptionsField.svelte"),
  multifieldselect: () => import("./forms/MultiFieldSelect.svelte"),
  booleanfield: () => import("./forms/BooleanField.svelte"),
  longformfield: () => import("./forms/LongFormField.svelte"),
  datetimefield: () => import("./forms/DateTimeField.svelte"),
  attachmentfield: () => import("./forms/AttachmentField.svelte"),
  attachmentsinglefield: () => import("./forms/AttachmentSingleField.svelte"),
  relationshipfield: () => import("./forms/RelationshipField.svelte"),
  passwordfield: () => import("./forms/PasswordField.svelte"),
  formstep: () => import("./forms/FormStep.svelte"),
  jsonfield: () => import("./forms/JSONField.svelte"),
  s3upload: () => import("./forms/S3Upload.svelte"),
  codescanner: () => import("./forms/CodeScannerField.svelte"),
  signaturesinglefield: () => import("./forms/SignatureField.svelte"),
  bbreferencefield: () => import("./forms/BBReferenceField.svelte"),
  bbreferencesinglefield: () => import("./forms/BBReferenceSingleField.svelte"),
  ratingfield: () => import("./forms/RatingField.svelte"),
  // Blocks
  cardsblock: () => import("./blocks/CardsBlock.svelte"),
  repeaterblock: () => import("./blocks/RepeaterBlock.svelte"),
  formblock: () => import("./blocks/form/FormBlock.svelte"),
  chartblock: () => import("./blocks/ChartBlock.svelte"),
  rowexplorer: () => import("./blocks/RowExplorer.svelte"),
  multistepformblock: () => import("./blocks/MultiStepFormblock.svelte"),
  // Dynamic filter
  dynamicfilter: () => import("./dynamic-filter/DynamicFilter.svelte"),
  // PDF
  pdf: () => import("./pdf/PDF.svelte"),
  pdftable: () => import("./pdf/PDFTable.svelte"),
  // Deprecated
  table: () => import("./deprecated/table/Table.svelte"),
  tableblock: () => import("./deprecated/TableBlock.svelte"),
  navigation: () => import("./deprecated/Navigation.svelte"),
  cardhorizontal: () => import("./deprecated/CardHorizontal.svelte"),
  stackedlist: () => import("./deprecated/StackedList.svelte"),
  card: () => import("./deprecated/Card.svelte"),
  section: () => import("./deprecated/Section.svelte"),
  text: () => import("./deprecated/Text.svelte"),
  heading: () => import("./deprecated/Heading.svelte"),
  markdownviewer: () => import("./deprecated/MarkdownViewer.svelte"),
}

export default componentLoaders
