apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app-service
  name: app-service
spec:
  replicas: {{ .Values.services.apps.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: app-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app-service
    spec:
      containers:
      - env:
        - name: BUDIBASE_ENVIRONMENT
          value: {{ .Values.globals.budibase_env }}
        - name: COUCH_DB_URL
          value: 10.96.145.235:5984
        - name: ENABLE_ANALYTICS
          value: {{ .Values.globals.enable_analytics }}
        - name: INTERNAL_API_KEY
          value: {{ .Values.globals.internal_api_key }}
        - name: JWT_SECRET
          value: {{ .Values.globals.jwt_secret }}
        - name: LOG_LEVEL
          value: {{ .Values.services.apps.log_level | default "info" | quote }}
        - name: MINIO_ACCESS_KEY
          value: "budibase"
        - name: MINIO_SECRET_KEY
          value: "budibase"
        - name: MINIO_URL
          value: 10.109.95.227:9000
        - name: PORT
          value: {{ .Values.services.apps.port }}
        - name: REDIS_PASSWORD
          value: "budibase"
        - name: REDIS_URL
          value: 10.104.121.14:6379
        - name: SELF_HOSTED
          value: {{ .Values.globals.self_hosted | default "1" | quote }}
        - name: SENTRY_DSN
          value: {{ .Values.globals.sentry_dsn }}
        - name: WORKER_URL
          value: 10.101.122.74:4003
        image: budibase/apps:develop
        imagePullPolicy: ""
        name: bbapps
        ports:
        - containerPort: {{ .Values.services.apps.port }}
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: app-service-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: app-service-claim0
        persistentVolumeClaim:
          claimName: app-service-claim0
status: {}
