services:
  app-service:
    image: budibase/apps:v1.2.3-hotfix3
    pull_policy: never

  worker-service:
    image: budibase/worker:v1.2.3-hotfix1
    pull_policy: never

  proxy-service:
    image: budibase/proxy:v1.2.3-hotfix2
    pull_policy: never
    environment:
      - RESOLVER=10.89.0.1
