general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  drop_params: true
  extra_spend_tag_headers:
    - "x-litellm-tags"
  disable_add_user_agent_to_request_tags: true
  num_retries: 3
  retry_after: 5
  retry_policy:
    RateLimitErrorRetries: 4
