import "./_style.scss";
export { default as body1 } from "./Body1.svelte";
export { default as body2 } from "./Body2.svelte";
export { default as caption } from "./Caption.svelte";
export { default as h1 } from "./H1.svelte";
export { default as h2 } from "./H2.svelte";
export { default as h3 } from "./H3.svelte";
export { default as h4 } from "./H4.svelte";
export { default as h5 } from "./H5.svelte";
export { default as h6 } from "./H6.svelte";
export { default as overline } from "./Overline.svelte";
export { default as sub1 } from "./Sub1.svelte";
export { default as sub2 } from "./Sub2.svelte";
