apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy-service
  name: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy-service
    spec:
      containers:
      - image: envoyproxy/envoy:v1.16-latest
        imagePullPolicy: ""
        name: proxy-service
        ports:
        - containerPort: 10000
        resources: {}
        volumeMounts:
        - mountPath: /etc/envoy/envoy.yaml
          name: proxy-service-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: proxy-service-claim0
        persistentVolumeClaim:
          claimName: proxy-service-claim0
status: {}
