apiVersion: v1
kind: Service
metadata:
  annotations:
    com.centurylinklabs.watchtower.enable: "false"
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: watchtower-service
  name: watchtower-service
spec:
  ports:
  - name: "6161"
    port: 6161
    targetPort: 8080
  selector:
    io.kompose.service: watchtower-service
status:
  loadBalancer: {}
