export const Actions = {
  SUMMARIZE_TEXT: "SUMMARIZE_TEXT",
  GENERATE_SQL: "GENERATE_SQL",
  GENERATE_CODE: "GENERATE_CODE",
  GENERATE_TABLE_SCHEMA: "GENERATE_TABLE_SCHEMA",
  GENERATE_SCREEN: "GENERATE_SCREEN",
}

export const Models = {
  ChatGPT: "ChatGPT",
  GPT4All: "GPT4All",
  TogetherAI: "TogetherAI",
  LlamaCPP: "LlamaCPP"
}
