export const Actions = {
  SUMMARIZE_TEXT: "SUMMARIZE_TEXT",
  GENERATE_SQL: "GENERATE_SQL",
  GENERATE_CODE: "GENERATE_CODE",
  GENERATE_TABLE_SCHEMA: "GENERATE_TABLE_SCHEMA",
  GENERATE_SCREEN: "GENERATE_SCREEN",
  GENERATE_AUTOMATION: "GENERATE_AUTOMATION",
}

export const Schemas = {
  SUMMARIZE_TEXT: {},
  GENERATE_SQL: {},
  GENERATE_CODE: {},
  GENERATE_TABLE_SCHEMA: {},
  GENERATE_SCREEN: {},
  GENERATE_AUTOMATION: {},
}

export const Models = {
  OPENAI: "OpenAI",
  LLAMA_CPP: "Llama.cpp"
}
