<script>
  import { Select, ModalContent } from "@budibase/bbui"
  import { RoleUtils } from "@budibase/frontend-core"
  import { roles } from "stores/backend"
  import { get } from "svelte/store"
  import { store } from "builderStore"
  import { onMount } from "svelte"

  import { _ } from "lang/i18n"

  export let onConfirm
  export let onCancel
  export let screenUrl
  export let screenAccessRole

  let error

  const onChangeRole = e => {
    const roleId = e.detail
    if (routeExists(screenUrl, roleId)) {
      error = $_(
        "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.URL_taken"
      )
    } else {
      error = null
    }
  }

  const routeExists = (url, role) => {
    if (!url || !role) {
      return false
    }
    return get(store).screens.some(
      screen =>
        screen.routing.route.toLowerCase() === url.toLowerCase() &&
        screen.routing.roleId === role
    )
  }

  onMount(() => {
    // Validate the initial role
    onChangeRole({ detail: screenAccessRole })
  })
</script>

<ModalContent
  title={$_(
    "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.Autogenerated_screens"
  )}
  confirmText={$_(
    "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.Done"
  )}
  cancelText={$_(
    "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.Back"
  )}
  {onConfirm}
  {onCancel}
  disabled={!!error}
>
  {$_(
    "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.level_access"
  )}
  <Select
    bind:value={screenAccessRole}
    on:change={onChangeRole}
    label={$_(
      "pages.builder.app.application.design.screenId.screens._components.ScreenRoleModal.Access"
    )}
    {error}
    getOptionLabel={role => role.name}
    getOptionValue={role => role._id}
    getOptionColour={role => RoleUtils.getRoleColour(role._id)}
    options={$roles}
    placeholder={null}
  />
</ModalContent>
