<script>
  import { Body, Input, Select, ModalContent } from "@budibase/bbui"

  export let options
  export let selected
  export let email = ""
  export let onConfirm
  export let disabled
</script>

<ModalContent
  {onConfirm}
  size="M"
  title="Add new user options"
  confirmText="Add user"
  confirmDisabled={disabled}
  cancelText="Cancel"
  showCloseIcon={false}
>
  <Body noPadding
    >If you have SMTP configured and an email for the new user, you can use the
    automated email onboarding flow. Otherwise, use our basic onboarding process
    with autogenerated passwords.</Body
  >
  <Select
    placeholder={null}
    bind:value={selected}
    {options}
    label="Add new user via:"
  />
  <Input
    type="email"
    bind:value={email}
    placeholder="john@doe.com"
    label="Email"
  />
</ModalContent>
