<script>
  import {
    Body,
    Input,
    Select,
    ModalContent,
    notifications,
    Toggle,
    Label,
  } from "@budibase/bbui"
  import { createValidationStore, emailValidator } from "helpers/validation"
  import { users } from "stores/portal"
  import { _ as t } from "svelte-i18n"

  export let disabled

  const options = ["Email onboarding", "Basic onboarding"]
  let selected = options[0]
  let builder, admin

  const [email, error, touched] = createValidationStore("", emailValidator)

  async function createUserFlow() {
    const res = await users.invite({ email: $email, builder, admin })
    if (res.status) {
      notifications.error(res.message)
    } else {
      notifications.success(res.message)
    }
  }
</script>

<ModalContent
  onConfirm={createUserFlow}
  size="M"
  title={ $t('add-new-user') }
  confirmText={ $t('add-user') }
  confirmDisabled={disabled}
  cancelText={ $t('cancel') }
  disabled={$error}
  showCloseIcon={false}
>
  <Body size="S">
    { $t('if-you-have-smtp-configured-and-an-email-for-the-new-user-you-can-use-the-automated-email-onboarding-flow-otherwise-use-our-basic-onboarding-process-with-autogenerated-passwords') }
  </Body>
  <Select
    placeholder={null}
    bind:value={selected}
    on:change
    {options}
    label={ $t('add-new-user-via') }
  />
  <Input
    type="email"
    bind:value={$email}
    error={$touched && $error}
    placeholder="john@doe.com"
    label={ $t('email') }
  />
  <div>
    <div class="toggle">
      <Label size="L">{ $t('development-access') }</Label>
      <Toggle text="" bind:value={builder} />
    </div>
    <div class="toggle">
      <Label size="L">{ $t('administration-access') }</Label>
      <Toggle text="" bind:value={admin} />
    </div>
  </div>
</ModalContent>

<style>
  .toggle {
    display: grid;
    grid-template-columns: 78% 1fr;
    align-items: center;
    width: 50%;
  }
</style>
