<script>
  import { Body, ModalContent, Table, Icon } from "@budibase/bbui"
  import PasswordCopyRenderer from "./PasswordCopyRenderer.svelte"

  export let userData

  $: mappedData = userData.map(user => {
    return {
      email: user.email,
      password: user.password,
    }
  })

  const schema = {
    email: {},
    password: {},
  }
</script>

<ModalContent
  size="S"
  title="Accounts created!"
  confirmText="Done"
  showCancelButton={false}
  cancelText="Cancel"
  showCloseIcon={false}
>
  <Body size="XS"
    >All your new users can be accessed through the autogenerated passwords.
    Make not of these passwords or download the csv</Body
  >

  <div class="container">
    <div class="inner">
      <Icon name="Download" />

      <div style="margin-left: var(--spacing-m)">
        <Body size="XS">Passwords CSV</Body>
      </div>
    </div>
  </div>

  <Table
    {schema}
    data={mappedData}
    allowEditColumns={false}
    allowEditRows={false}
    allowSelectRows={false}
    customRenderers={[{ column: "password", component: PasswordCopyRenderer }]}
  />
</ModalContent>

<style>
  .inner {
    display: flex;
  }

  :global(.spectrum-Picker) {
    border-top-left-radius: 0px;
  }

  .container {
    width: 100%;
    height: var(--spectrum-alias-item-height-l);
    background: #009562;
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
