export const cardsblock = () => import("./CardsBlock.svelte")
export const repeaterblock = () => import("./RepeaterBlock.svelte")
export const formblock = () => import("./form/FormBlock.svelte")
export const chartblock = () => import("./ChartBlock.svelte")
export const rowexplorer = () => import("./RowExplorer.svelte")
export const multistepformblock = () => import("./MultiStepFormblock.svelte")
