# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
