<script>
  import { Body, Input, Select, ModalContent } from "@budibase/bbui"

  const options = ["Email onboarding", "Basic onboarding"]
  let selected = options[0]
</script>

<ModalContent
  size="M"
  title="Add new user options"
  confirmText="Add user"
  cancelText="Cancel"
  showCloseIcon={false}
>
  <Body noPadding
    >If you have SMTP configured and an email for the new user, you can use the
    automated email onboarding flow. Otherwise, use our basic onboarding process
    with autogenerated passwords.</Body
  >
  <Select bind:value={selected} label="Add new user via:" {options} />
  <Input label="Email" />
</ModalContent>
