bind 0.0.0.0
protected-mode no
port 0
tls-port 6379
tls-cert-file /certs/server.crt
tls-key-file /certs/server.key
tls-ca-cert-file /certs/ca.crt
tls-auth-clients no
aclfile /usr/local/etc/redis/users.acl
dir /data
