export const APPROVAL_REQUIRED_TITLE_PREFIX = "Approval required:"
export const MAX_REVIEW_PARAMETERS = 40
export const MAX_REVIEW_PARAMETER_NAME_LENGTH = 250

export const ESCALATION_DURATION_PRESETS = {
  ONE_DAY: 86400,
  THREE_DAYS: 259200,
  ONE_WEEK: 604800,
  THIRTY_DAYS: 2592000,
  NINETY_DAYS: 7776000,
} as const

export const DEFAULT_ESCALATION_DURATION_SECONDS =
  ESCALATION_DURATION_PRESETS.ONE_DAY
