#!/bin/bash
# generate-hardened-dockerfile.sh
#
# Generates Dockerfile.hardened for server, worker, and couchdb from their
# respective source Dockerfiles using Python-based text transformations.
#
# Integrates:
#   - Phase 1 npm patches (package.hardened.json) via COPY substitution
#   - OS-level CVE fixes (zlib CVE-2026-22184, curl CVE-2026-3805)
#   - Non-root USER directive (server/worker only)
#   - Native addon smoke test (bcrypt, isolated-vm)
#
# Usage: bash scripts/generate-hardened-dockerfile.sh
#
# Idempotent: running twice produces identical output.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# generate_alpine: produce Dockerfile.hardened for an Alpine-based node image
#   $1 = absolute path to source Dockerfile
#   $2 = package directory name (e.g. "packages/server")
generate_alpine() {
  local SRC="$1"
  local PKG_DIR="$2"
  local OUT
  OUT="$(dirname "$SRC")/Dockerfile.hardened"

  python3 - "$SRC" "$PKG_DIR" "$OUT" <<'PYEOF'
import sys
import re

src_path = sys.argv[1]
pkg_dir  = sys.argv[2]
out_path = sys.argv[3]

with open(src_path) as f:
    lines = f.readlines()

HEADER = "# AUTO-GENERATED by scripts/generate-hardened-dockerfile.sh \u2014 do not edit manually\n"

OS_PATCH_BLOCK = """\
# OS-level CVE patches \u2014 scoped to named packages only (OS-01, OS-02, OS-03)
# zlib 1.3.2-r0: fixes CVE-2026-22184 (CRITICAL) \u2014 Alpine 3.23 stable
# curl 8.19.0-r0: fixes CVE-2026-3805 (HIGH) \u2014 requires Alpine edge/main
RUN apk add --upgrade --no-cache \\
    --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main \\
    zlib \\
    curl

"""

USER_BLOCK = """\
# Smoke test: verify native addons survive OS package upgrade
RUN node -e "require('bcrypt'); require('isolated-vm'); console.log('native addons OK')"

# Drop to non-root user (DOCK-05)
# node user (UID 1000) pre-exists in node:22-alpine
RUN chown -R node:node /app
USER node

"""

out_lines = [HEADER]

for line in lines:
    # 1. Insert OS patch block BEFORE '# handle node-gyp'
    if line.strip().startswith("# handle node-gyp"):
        out_lines.append(OS_PATCH_BLOCK)

    # 2. Replace COPY package.json with COPY package.hardened.json
    pkg_copy_pattern = rf"^COPY {re.escape(pkg_dir)}/package\.json\s+\.\s*$"
    if re.match(pkg_copy_pattern, line):
        line = f"COPY {pkg_dir}/package.hardened.json ./package.json\n"

    # 3. Insert smoke test + chown + USER before CMD
    if re.match(r'^CMD\s+', line):
        out_lines.append(USER_BLOCK)

    out_lines.append(line)

content = "".join(out_lines)

with open(out_path, "w") as f:
    f.write(content)
PYEOF

  # Post-generation assertions
  if ! grep -q 'package\.hardened\.json' "$OUT"; then
    echo "ERROR: $OUT does not contain 'package.hardened.json' — substitution failed" >&2
    exit 1
  fi
  if ! grep -q 'removeWorkspaceDependencies' "$OUT"; then
    echo "ERROR: $OUT does not contain 'removeWorkspaceDependencies' — COPY sequence was dropped" >&2
    exit 1
  fi
  if ! grep -q 'USER node' "$OUT"; then
    echo "ERROR: $OUT does not contain 'USER node' directive (DOCK-05)" >&2
    exit 1
  fi
  if ! grep -q 'apk add --upgrade' "$OUT"; then
    echo "ERROR: $OUT does not contain 'apk add --upgrade' (OS-01, OS-02)" >&2
    exit 1
  fi
  if ! grep -q 'alpine/edge/main' "$OUT"; then
    echo "ERROR: $OUT does not contain Alpine edge/main repository URL (OS-02)" >&2
    exit 1
  fi

  echo "Written: $OUT"
}

# generate_couchdb: produce Dockerfile.hardened for the Debian-based CouchDB image
#   $1 = absolute path to source Dockerfile
generate_couchdb() {
  local SRC="$1"
  local OUT
  OUT="$(dirname "$SRC")/Dockerfile.hardened"

  python3 - "$SRC" "$OUT" <<'PYEOF'
import sys

src_path = sys.argv[1]
out_path = sys.argv[2]

HEADER = "# AUTO-GENERATED by scripts/generate-hardened-dockerfile.sh \u2014 do not edit manually\n"

with open(src_path) as f:
    content = f.read()

with open(out_path, "w") as f:
    f.write(HEADER + content)
PYEOF

  # Post-generation assertion
  if ! grep -q 'apt-mark hold couchdb' "$OUT"; then
    echo "ERROR: $OUT does not contain 'apt-mark hold couchdb' — CouchDB OS patch pattern missing (D-07)" >&2
    exit 1
  fi

  echo "Written: $OUT"
}

# Generate all three Dockerfile.hardened files
generate_alpine "$REPO_ROOT/packages/server/Dockerfile" "packages/server"
generate_alpine "$REPO_ROOT/packages/worker/Dockerfile" "packages/worker"
generate_couchdb "$REPO_ROOT/hosting/couchdb/Dockerfile"
