<script lang="ts">
  import { Body, ModalContent, Table, Icon } from "@budibase/bbui"
  import PasswordCopyTableRenderer from "./PasswordCopyTableRenderer.svelte"
  import { parseToCsv } from "@/helpers/data/utils"
  import InviteResponseRenderer from "./InviteResponseRenderer.svelte"
  import type { BulkUserCreated } from "@budibase/types"

  interface Props {
    userData: { email: string; password: string }[]
    createUsersResponse: BulkUserCreated
    addedToWorkspaceEmails?: string[]
  }

  let {
    userData,
    createUsersResponse,
    addedToWorkspaceEmails = [],
  }: Props = $props()
  const MAX_VISIBLE_PASSWORD_ROWS = 10
  const MAX_VISIBLE_FAILURE_ROWS = 10

  const hasSuccess = $derived(createUsersResponse.successful.length > 0)
  const hasFailure = $derived(createUsersResponse.unsuccessful.length > 0)
  const title = $derived(hasSuccess ? "Users created!" : "Oops!")
  const shouldShowPasswordsTable = $derived(
    createUsersResponse.successful.length <= MAX_VISIBLE_PASSWORD_ROWS
  )
  const shouldShowFailuresTable = $derived(
    createUsersResponse.unsuccessful.length <= MAX_VISIBLE_FAILURE_ROWS
  )
  const failureMessage = $derived.by(() => {
    const failureCount = createUsersResponse.unsuccessful.length
    const includeFailureCount = failureCount > MAX_VISIBLE_FAILURE_ROWS
    const countSuffix = includeFailureCount ? ` (${failureCount}).` : "."

    if (hasSuccess) {
      return `However there was a problem creating some users${countSuffix}`
    }
    return `There was a problem creating some users${countSuffix}`
  })
  const userDataIndex = $derived(
    userData.reduce<Record<string, { password: string }>>((prev, current) => {
      prev[current.email] = current
      return prev
    }, {})
  )
  const successfulUsers = $derived(
    createUsersResponse.successful.map(user => ({
      email: user.email,
      password: userDataIndex[user.email].password,
    }))
  )
  const unsuccessfulUsers = $derived(
    createUsersResponse.unsuccessful.map(user => ({
      email: user.email,
      reason: user.reason,
    }))
  )
  const addedToWorkspaceUsers = $derived(
    addedToWorkspaceEmails.map(email => ({ email }))
  )

  const successSchema = {
    email: {},
    password: {},
  }

  const failedSchema = {
    email: {},
    reason: {},
  }

  const workspaceAddedSchema = {
    email: {},
  }

  const downloadCsvFile = () => {
    const fileName = "passwords.csv"
    const content = parseToCsv(["email", "password"], successfulUsers)

    download(fileName, content)
  }

  const download = (filename: string, text: string) => {
    const element = document.createElement("a")
    element.setAttribute(
      "href",
      "data:text/csv;charset=utf-8," + encodeURIComponent(text)
    )
    element.setAttribute("download", filename)

    element.style.display = "none"
    document.body.appendChild(element)

    element.click()

    document.body.removeChild(element)
  }
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<!-- svelte-ignore a11y-click-events-have-key-events -->
<ModalContent
  size="L"
  {title}
  confirmText="Done"
  showCancelButton={false}
  cancelText="Cancel"
  showCloseIcon={false}
>
  {#if hasFailure}
    <Body size="S">
      {failureMessage}
    </Body>
    {#if shouldShowFailuresTable}
      <Table
        schema={failedSchema}
        data={unsuccessfulUsers}
        allowEditColumns={false}
        allowEditRows={false}
        allowSelectRows={false}
        customRenderers={[
          { column: "reason", component: InviteResponseRenderer },
        ]}
      />
    {/if}
  {/if}
  {#if hasSuccess}
    <Body size="XS">
      All your new users can be accessed through the autogenerated passwords.
      Take note of these passwords or download the CSV file.
    </Body>

    <div class="container" on:click={downloadCsvFile}>
      <div class="inner">
        <Icon name="download" />

        <div style="margin-left: var(--spacing-m)">
          <Body size="XS">Passwords CSV</Body>
        </div>
      </div>
    </div>

    {#if shouldShowPasswordsTable}
      <Table
        schema={successSchema}
        data={successfulUsers}
        allowEditColumns={false}
        allowEditRows={false}
        allowSelectRows={false}
        customRenderers={[
          { column: "password", component: PasswordCopyTableRenderer },
        ]}
      />
    {:else}
      <Body size="S">{successfulUsers.length} users added</Body>
    {/if}

    {#if addedToWorkspaceUsers.length}
      <Body size="XS">
        Existing organisation users added to this workspace:
      </Body>
      <Table
        schema={workspaceAddedSchema}
        data={addedToWorkspaceUsers}
        allowEditColumns={false}
        allowEditRows={false}
        allowSelectRows={false}
      />
    {/if}
  {/if}
</ModalContent>

<style>
  .inner {
    display: flex;
  }

  .container {
    width: 100%;
    height: var(--spectrum-alias-item-height-l);
    background: #009562;
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
