module.exports = {
  table: require("../../api/controllers/table"),
  row: require("../../api/controllers/row"),
  role: require("../../api/controllers/role"),
  perms: require("../../api/controllers/permission"),
  view: require("../../api/controllers/view"),
  app: require("../../api/controllers/application"),
  user: require("../../api/controllers/user"),
  automation: require("../../api/controllers/automation"),
  datasource: require("../../api/controllers/datasource"),
  query: require("../../api/controllers/query"),
  screen: require("../../api/controllers/screen"),
  webhook: require("../../api/controllers/webhook"),
  layout: require("../../api/controllers/layout"),
}
