export enum FeatureFlag {
  PER_CREATOR_PER_USER_PRICE = "PER_CREATOR_PER_USER_PRICE",
  PER_CREATOR_PER_USER_PRICE_ALERT = "PER_CREATOR_PER_USER_PRICE_ALERT",
  AUTOMATION_BRANCHING = "AUTOMATION_BRANCHING",
  AI_CUSTOM_CONFIGS = "AI_CUSTOM_CONFIGS",
  DEFAULT_VALUES = "DEFAULT_VALUES",

  BUDIBASE_AI = "BUDIBASE_AI",
}

export interface TenantFeatureFlags {
  [key: string]: FeatureFlag[]
}
