export enum JobQueue {
  AUTOMATION = "automationQueue",
  APP_BACKUP = "appBackupQueue",
  AUDIT_LOG = "auditLogQueue",
  SYSTEM_EVENT_QUEUE = "systemEventQueue",
  APP_MIGRATION = "appMigration",
  DOC_WRITETHROUGH_QUEUE = "docWritethroughQueue",
  DEV_REVERT_PROCESSOR = "devRevertProcessorQueue",
  BATCH_USER_SYNC_PROCESSOR = "batchUserSyncProcessorQueue",
  RAG_INGESTION = "ragIngestionQueue",
  KNOWLEDGE_SOURCE_SYNC = "knowledgeSourceSyncQueue",
  AGENT_LOG_INDEXING = "agentLogIndexingQueue",
  ESCALATION = "escalationQueue",
  AGENT_REQUEST_TRACKING = "agentRequestTrackingQueue",
  AGENT_TEST_RUN = "agentTestRunQueue",
}
