name: check_unreleased_changes

on:
  pull_request:
    branches:
      - master

jobs:
  check_unreleased:
    runs-on: ubuntu-latest
    steps:
      - name: Check for unreleased changes
        env:
          REPO: "Budibase/budibase"
          TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          RELEASE_TIMESTAMP=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/releases/latest" | \
              jq -r .published_at)
          COMMIT_TIMESTAMP=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/commits/master" | \
              jq -r .commit.committer.date)
          RELEASE_SECONDS=$(date --date="$RELEASE_TIMESTAMP" "+%s")
          COMMIT_SECONDS=$(date --date="$COMMIT_TIMESTAMP" "+%s")
          if (( COMMIT_SECONDS > RELEASE_SECONDS )); then
              echo "There are unreleased changes. Please release these changes before merging."
              exit 1
          fi
          echo "No unreleased changes detected."
