name: "deploy-preprod"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Budibase release version. For example - 1.0.0
        required: false
  workflow_call:

jobs:
  deploy-to-legacy-preprod-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the latest budibase release version
        id: version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            git pull
            release_version=$(cat lerna.json | jq -r '.version')
          else
            release_version=${{ github.event.inputs.version }}
          fi
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Pull values.yaml from budibase-infra
        run: |
          curl -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o values.preprod.yaml \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/kubernetes/budibase-preprod/values.yaml
          wc -l values.preprod.yaml

      - name: Deploy to Preprod Environment
        uses: budibase/helm@v1.8.0
        with:
          release: budibase-preprod
          namespace: budibase
          chart: charts/budibase
          token: ${{ github.token }}
          helm: helm3
          values: |
            globals: 
              appVersion: v${{ env.RELEASE_VERSION }}
            ingress:
              enabled: true
              nginx: true
          value-files: >-
            [
              "values.preprod.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.PREPROD_KUBECONFIG }}'

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.PROD_DEPLOY_WEBHOOK_URL }}
          content: "Preprod Deployment Complete: ${{ env.RELEASE_VERSION }} deployed to Budibase Pre-prod."
          embed-title: ${{ env.RELEASE_VERSION }}