name: Deploy QA

on:
  push:
    branches:
      - master
      - BUDI-7641/push_v2_images_to_qa
  workflow_dispatch:

jobs:
  trigger-deploy-to-qa-env:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        env:
          PAYLOAD_VERSION: ${{ github.sha }}
          REF_NAME: ${{ github.ref_name}}
        with:
          repository: budibase/budibase-deploys
          event-type: budicloud-qa-deploy-v2
          token: ${{ secrets.GH_ACCESS_TOKEN }}
