name: "deploy-preprod"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-to-legacy-preprod-env:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Pull values.yaml from budibase-infra
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PERSONAL_TOKEN }}" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o values.preprod.yaml \
          -L https://api.github.com/repos/budibase/budibase-infra/contents/kubernetes/budibase-preprod/values.yaml
          wc -l values.preprod.yaml

      - name: Deploy to Preprod Environment
        uses: budibase/helm@v1.8.0
        with:
          release: budibase-preprod
          namespace: budibase
          chart: charts/budibase
          token: ${{ github.token }}
          helm: helm3
          values: |
            globals: 
              appVersion: ${{ steps.previoustag.outputs.tag }}
            ingress:
              enabled: true
              nginx: true
          value-files: >-
            [
              "values.preprod.yaml"
            ]

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.PROD_DEPLOY_WEBHOOK_URL }}
          content: "Preprod Deployment Complete: ${{ steps.previoustag.outputs.tag }} deployed to Budibase Pre-prod."
          embed-title: ${{ steps.previoustag.outputs.tag }}