name: Tag prerelease
concurrency:
  group: tag-prerelease
  cancel-in-progress: false

on:
  push:
    branches:
      - develop
    paths:
      - ".aws/**"
      - ".github/**"
      - "charts/**"
      - "packages/**"
      - "scripts/**"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  tag-prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if branch is not develop
        if: github.ref != 'refs/heads/develop'
        run: |
          echo "Ref is not develop, you must run this job from develop."
          exit 1
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: yarn
      - name: Tag prerelease
        run: |
          # setup the username and email.
          git config --global user.name "Budibase Staging Release Bot"
          git config --global user.email "<>"
          ./scripts/versionCommit.sh prerelease
