name: Test release

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: Release notes
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print release notes
        env:
          RELEASE_NOTES: ${{ inputs.release_notes }}
        run: echo "$RELEASE_NOTES"
